apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sszrq0675-go 
  janus-idp.io/tekton: sszrq0675-go
  backstage.io/kubernetes-id: sszrq0675-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sszrq0675-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  