apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sszrq0675-go-gitops
  description: This is GitOps manifest for sszrq0675-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: sszrq0675-go
    backstage.io/kubernetes-id: sszrq0675-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: sszrq0675-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:sszrq0675-go
